name: Send ping to update Website

on:
  push:
  repository_dispatch:

jobs:
 dispatch:
    strategy:
      matrix:
        repo: ['Big-Install-Guide/Website']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch PING
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.LIMITED_PAT }}
          repository: ${{ matrix.repo }}
          event-type: ping
          # TESTTT