name: Send ping to update 'Website'

on:
  push:
  repository_dispatch:

jobs:
 dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch PING
        uses: ghost-420/trigger-workflow-and-wait
        with:
          github_token: ${{ secrets.LIMITED_PAT }}
          repo: Big-Install-Guide/Website
          event_type: ping
          client_payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'